import type {
  Campaign,
  Character,
  Scene,
  SFXTrack,
  CinematicMacro,
  SavedEncounter,
} from '../types';

// Built-in Synthesizer SFX list
export const BUILTIN_SFX: SFXTrack[] = [
  { id: 'sfx-thunder', name: 'Trueno / Tormenta', category: 'environment', icon: 'Zap', soundType: 'synthesized', synthPreset: 'thunder' },
  { id: 'sfx-sword', name: 'Choque de Espadas', category: 'combat', icon: 'ShieldAlert', soundType: 'synthesized', synthPreset: 'sword_clash' },
  { id: 'sfx-magic', name: 'Hechizo Mágico', category: 'magic', icon: 'Sparkles', soundType: 'synthesized', synthPreset: 'magic_spell' },
  { id: 'sfx-gong', name: 'Gong de Combate', category: 'combat', icon: 'Swords', soundType: 'synthesized', synthPreset: 'gong' },
  { id: 'sfx-roar', name: 'Rugido de Monstruo', category: 'combat', icon: 'Skull', soundType: 'synthesized', synthPreset: 'monster_roar' },
  { id: 'sfx-door', name: 'Puerta Chirriante', category: 'mystery', icon: 'DoorOpen', soundType: 'synthesized', synthPreset: 'door_creak' },
  { id: 'sfx-bell', name: 'Campana de Templo', category: 'social', icon: 'Bell', soundType: 'synthesized', synthPreset: 'church_bell' },
  { id: 'sfx-fanfare', name: 'Fanfarria de Victoria', category: 'social', icon: 'Trophy', soundType: 'synthesized', synthPreset: 'fanfare_victory' },
  { id: 'sfx-heartbeat', name: 'Latido / Tensión', category: 'mystery', icon: 'Heart', soundType: 'synthesized', synthPreset: 'heartbeat' },
];

// Initial Demo Campaign Characters
export const DEMO_CHARACTERS: Character[] = [
  {
    id: 'char-eldrin',
    name: 'Eldrin Sombrasusurro',
    roleOrTitle: 'Pícaro Elfo Silvano',
    defaultAvatarUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    expressions: {
      'Neutral': 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
      'Alerta': 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    },
    bio: 'Un explorador sigiloso con conocimiento del bosque prohibido.',
    tags: ['Elfo', 'Pícaro', 'Aliado'],
    maxHp: 38,
  },
  {
    id: 'char-morwen',
    name: 'Morwen del Fuego Carmesí',
    roleOrTitle: 'Archimaga del Cónclave',
    defaultAvatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
    expressions: {
      'Serena': 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
      'Lanzando Magia': 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=600&auto=format&fit=crop&q=80',
    },
    bio: 'Custodia runas arcanas y secretos de la era primordial.',
    tags: ['Maga', 'Noble', 'Neutral'],
    maxHp: 32,
  },
  {
    id: 'char-thorin',
    name: 'Bromir Rompehierro',
    roleOrTitle: 'Capitán Enano Guardián',
    defaultAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
    expressions: {
      'Firme': 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
    },
    bio: 'Veterano de mil batallas subterráneas contra las hordas oscuras.',
    tags: ['Enano', 'Guerrero'],
    maxHp: 58,
  },
  {
    id: 'char-tavernero',
    name: 'Gromm el Tabernero',
    roleOrTitle: 'Dueño del Dragón Durmiente',
    defaultAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80',
    bio: 'Sabe todos los rumores de la región... a cambio de unas monedas de oro.',
    tags: ['NPC', 'Taberna'],
    maxHp: 24,
  },
  {
    id: 'char-ignis',
    name: 'Vaelthazar el Devorador',
    roleOrTitle: 'Dragón Anciano Rojo',
    defaultAvatarUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    bio: 'Reposa en su lecho de oro fundido esperando intrusos.',
    tags: ['Jefe', 'Dragón', 'Enemigo'],
    maxHp: 180,
  },
];

// Initial Demo Scenes
export const DEMO_SCENES: Scene[] = [
  {
    id: 'scene-tavern',
    name: 'Taberna del Dragón Durmiente',
    backgroundUrl: 'https://images.unsplash.com/photo-1572025442646-866d16c84a54?w=1600&auto=format&fit=crop&q=80',
    locationBanner: 'TABERNA DEL DRAGÓN DURMIENTE',
    subtitle: 'Valle de Oakhaven - Rumores y Cerveza Enana',
    weather: 'embers',
    weatherIntensity: 0.4,
    lighting: 'torch_flicker',
    dmNotes: 'El tabernero Gromm tiene la llave del sótano donde se oculta la entrada a las catacumbas.',
    ambientAudioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=medieval-tavern-music-112349.mp3',
    ambientAudioName: 'Música de Taberna Medieval',
    suggestedNpcIds: ['char-tavernero', 'char-eldrin'],
  },
  {
    id: 'scene-forest',
    name: 'Bosque de los Susurros',
    backgroundUrl: 'https://images.unsplash.com/photo-1511497584788-87676104235f?w=1600&auto=format&fit=crop&q=80',
    locationBanner: 'BOSQUE DE LOS SUSURROS',
    subtitle: 'Tierras Salvajes - Sendero de la Niebla Eterna',
    weather: 'fog',
    weatherIntensity: 0.7,
    lighting: 'mystic_violet',
    dmNotes: 'Tirada de Percepción DC 14 para no perderse.',
    ambientAudioUrl: 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3?filename=forest-wind-and-birds-6881.mp3',
    ambientAudioName: 'Viento en el Bosque Mágico',
    suggestedNpcIds: ['char-eldrin', 'char-morwen'],
  },
  {
    id: 'scene-storm-ruins',
    name: 'Ruinas de la Torre Quebrada',
    backgroundUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    locationBanner: 'RUINAS DE LA TORRE QUEBRADA',
    subtitle: 'Tempestad en el Paso del Trueno',
    weather: 'storm',
    weatherIntensity: 0.9,
    lighting: 'night',
    dmNotes: 'Lluvia intensa y relámpagos constantes.',
    ambientAudioUrl: 'https://cdn.pixabay.com/download/audio/2022/10/30/audio_51c6b6d510.mp3?filename=heavy-rain-and-thunder-126296.mp3',
    ambientAudioName: 'Lluvia Fuerte y Truenos',
    suggestedNpcIds: ['char-morwen', 'char-thorin'],
  },
  {
    id: 'scene-dragon-lair',
    name: 'Guarida de Vaelthazar',
    backgroundUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1600&auto=format&fit=crop&q=80',
    locationBanner: 'SANTUARIO DEL FUEGO ETERNO',
    subtitle: 'Corazón Volcánico de la Montaña Roja',
    weather: 'embers',
    weatherIntensity: 1.0,
    lighting: 'blood_moon',
    dmNotes: 'El suelo está cubierto de oro y huesos calcinados.',
    suggestedNpcIds: ['char-ignis', 'char-morwen'],
  },
];

// Initial Demo Macros
export const DEMO_MACROS: CinematicMacro[] = [
  {
    id: 'macro-dragon-awakens',
    name: 'Despertar de Vaelthazar',
    description: 'Blackout, rugido aterrador, temblor y revelación del dragón ancestral entre ascuas y fuego carmesí.',
    icon: 'Skull',
    steps: [
      {
        id: 'step-1',
        delayMs: 1800,
        actionLabel: 'Blackout & Rugido Aterrador',
        blackout: true,
        sfxPreset: 'monster_roar',
        shake: true,
      },
      {
        id: 'step-2',
        delayMs: 0,
        actionLabel: 'Revelación del Santuario del Dragón',
        sceneId: 'scene-dragon-lair',
        backgroundUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1600&auto=format&fit=crop&q=80',
        weather: 'embers',
        weatherIntensity: 1.0,
        lighting: 'blood_moon',
        blackout: false,
        locationBanner: {
          text: '¡DESPIERTA VAELTHAZAR!',
          subtitle: 'Corazón Volcánico de la Montaña Roja',
          visible: true,
        },
        charactersToAdd: [
          {
            id: 'macro-char-dragon',
            characterId: 'char-ignis',
            name: 'Vaelthazar el Devorador',
            avatarUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
            position: 'center-right',
            isSpeaking: true,
          },
        ],
        sfxPreset: 'thunder',
        shake: true,
      },
    ],
  },
  {
    id: 'macro-ruins-storm',
    name: 'Tempestad en las Ruinas',
    description: 'Tormenta nocturna, relámpago con trueno y llegada de Bromir en posición de guardia.',
    icon: 'CloudLightning',
    steps: [
      {
        id: 'step-1',
        delayMs: 1400,
        actionLabel: 'Comienzo de la Tormenta',
        sceneId: 'scene-storm-ruins',
        backgroundUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
        weather: 'storm',
        weatherIntensity: 0.9,
        lighting: 'night',
        ambientAudioUrl: 'https://cdn.pixabay.com/download/audio/2022/10/30/audio_51c6b6d510.mp3?filename=heavy-rain-and-thunder-126296.mp3',
        ambientAudioName: 'Lluvia Fuerte y Truenos',
        ambientPlaying: true,
        ambientVolume: 0.6,
      },
      {
        id: 'step-2',
        delayMs: 0,
        actionLabel: 'Rayo & Aparición del Capitán Enano',
        lightning: true,
        shake: true,
        sfxPreset: 'thunder',
        locationBanner: {
          text: 'RUINAS DE LA TORRE QUEBRADA',
          subtitle: 'Tempestad en el Paso del Trueno',
          visible: true,
        },
        charactersToAdd: [
          {
            id: 'macro-char-thorin',
            characterId: 'char-thorin',
            name: 'Bromir Rompehierro',
            avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
            position: 'center-left',
            isSpeaking: false,
          },
        ],
      },
    ],
  },
  {
    id: 'macro-tavern-arrival',
    name: 'Llegada a la Taberna',
    description: 'Campanadas de fondo, calor de antorchas, música festiva y bienvenida del tabernero Gromm.',
    icon: 'Flame',
    steps: [
      {
        id: 'step-1',
        delayMs: 1200,
        actionLabel: 'Campana & Puerta',
        sfxPreset: 'church_bell',
      },
      {
        id: 'step-2',
        delayMs: 0,
        actionLabel: 'Ambiente Cálido y Bienvenida',
        sceneId: 'scene-tavern',
        backgroundUrl: 'https://images.unsplash.com/photo-1572025442646-866d16c84a54?w=1600&auto=format&fit=crop&q=80',
        weather: 'embers',
        weatherIntensity: 0.4,
        lighting: 'torch_flicker',
        ambientAudioUrl: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=medieval-tavern-music-112349.mp3',
        ambientAudioName: 'Música de Taberna Medieval',
        ambientPlaying: true,
        ambientVolume: 0.5,
        locationBanner: {
          text: 'TABERNA DEL DRAGÓN DURMIENTE',
          subtitle: 'Valle de Oakhaven - Rumores y Cerveza Enana',
          visible: true,
        },
        charactersToAdd: [
          {
            id: 'macro-char-tavernero',
            characterId: 'char-tavernero',
            name: 'Gromm el Tabernero',
            avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&auto=format&fit=crop&q=80',
            position: 'center-left',
            isSpeaking: true,
          },
        ],
      },
    ],
  },
];

// Initial Demo Saved Encounters
export const DEMO_ENCOUNTERS: SavedEncounter[] = [
  {
    id: 'enc-wolves',
    campaignId: 'campaign-demo',
    name: 'Emboscada de los Lobos Sombríos',
    description: 'Una jauría de lobos hambrientos rodea el campamento mientras el lobo alfa acecha en las sombras.',
    difficulty: 'medio',
    rewardsSummary: '350 XP, 45 PO, 2 Pieles de Lobo Huargo de Calidad',
    turnTimerSeconds: 60,
    dmNotes: 'Los lobos atacan en manada (tienen ventaja si hay otro lobo a 1.5m de la víctima). El Alfa entra en la Ronda 2.',
    combatants: [
      {
        id: 'wolf-1',
        name: 'Lobo Huargo A',
        avatarUrl: 'https://images.unsplash.com/photo-1564865878688-9a244444042a?w=600&auto=format&fit=crop&q=80',
        maxHp: 26,
        currentHp: 26,
        isMonster: true,
        showHpToPlayers: false,
        initiativeType: 'roll_d20',
        initiativeModifier: 2,
      },
      {
        id: 'wolf-2',
        name: 'Lobo Huargo B',
        avatarUrl: 'https://images.unsplash.com/photo-1564865878688-9a244444042a?w=600&auto=format&fit=crop&q=80',
        maxHp: 26,
        currentHp: 26,
        isMonster: true,
        showHpToPlayers: false,
        initiativeType: 'roll_d20',
        initiativeModifier: 2,
      },
      {
        id: 'wolf-alpha',
        name: '🐺 Lobo Alfa Garraoscura (Refuerzo)',
        avatarUrl: 'https://images.unsplash.com/photo-1590424744299-eb38b97d264e?w=600&auto=format&fit=crop&q=80',
        maxHp: 48,
        currentHp: 48,
        isMonster: true,
        showHpToPlayers: false,
        initiativeType: 'roll_d20',
        initiativeModifier: 3,
        isWaveReinforcement: true,
        triggerRound: 2,
      },
      {
        id: 'player-eldrin',
        name: 'Eldrin Sombrasusurro',
        avatarUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
        maxHp: 38,
        currentHp: 38,
        isMonster: false,
        showHpToPlayers: true,
        initiativeType: 'roll_d20',
        initiativeModifier: 4,
      },
      {
        id: 'player-bromir',
        name: 'Bromir Rompehierro',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&auto=format&fit=crop&q=80',
        maxHp: 58,
        currentHp: 58,
        isMonster: false,
        showHpToPlayers: true,
        initiativeType: 'roll_d20',
        initiativeModifier: 1,
      },
    ],
  },
  {
    id: 'enc-dragon',
    campaignId: 'campaign-demo',
    name: 'El Juicio de Vaelthazar el Devorador',
    description: 'Enfrentamiento culminante contra el dragón anciano en su trono de lava ardiente.',
    difficulty: 'letal',
    rewardsSummary: '3.800 XP, 2.400 PO, Corona de Rubíes del Rey Enano, Daga Llameante +2',
    turnTimerSeconds: 60,
    dmNotes: 'Aliento de Fuego (Recarga 5-6): 12d6 daño de fuego en cono de 18m (DC 18 Destreza mitad).',
    combatants: [
      {
        id: 'boss-vaelthazar',
        name: '🐉 Vaelthazar el Devorador',
        avatarUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
        maxHp: 180,
        currentHp: 180,
        isMonster: true,
        showHpToPlayers: true,
        initiativeType: 'fixed',
        fixedInitiative: 20,
      },
      {
        id: 'cultist-1',
        name: 'Fanático del Fuego A',
        avatarUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=600&auto=format&fit=crop&q=80',
        maxHp: 32,
        currentHp: 32,
        isMonster: true,
        showHpToPlayers: false,
        initiativeType: 'roll_d20',
        initiativeModifier: 2,
      },
      {
        id: 'cultist-2',
        name: 'Fanático del Fuego B (Refuerzo)',
        avatarUrl: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=600&auto=format&fit=crop&q=80',
        maxHp: 32,
        currentHp: 32,
        isMonster: true,
        showHpToPlayers: false,
        initiativeType: 'roll_d20',
        initiativeModifier: 2,
        isWaveReinforcement: true,
        triggerRound: 3,
      },
      {
        id: 'p-morwen',
        name: 'Morwen del Fuego Carmesí',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80',
        maxHp: 32,
        currentHp: 32,
        isMonster: false,
        showHpToPlayers: true,
        initiativeType: 'roll_d20',
        initiativeModifier: 2,
      },
    ],
  },
];

export const DEMO_CAMPAIGN: Campaign = {
  id: 'campaign-demo',
  title: 'La Crónica de las Gemas de Fuego',
  description: 'Aventura de prueba que viaja desde una cálida taberna hasta la guarida de un dragón milenario cruzando bosques y tempestades.',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  scenes: DEMO_SCENES,
  characters: DEMO_CHARACTERS,
  customSfx: BUILTIN_SFX,
  macros: DEMO_MACROS,
  encounters: DEMO_ENCOUNTERS,
};
